level: class
info: >-
  Most amphibians live within aquatic ecosystems.  They usually start out as larva in water, then
  undergo metamorphosis from gill-breathing young to air-breathing adults with lungs.  Amphibians
  use their skin as a secondary respiratory surface, and some also lack lungs.  They are
  superficially similar to reptiles, but unlike reptiles, amphibians require water bodies in which
  to breed.
