level: superclass
common: Bony fish
info: >-
  Bony fish are fish with skeletons made out of bone, rather than cartilege.  This group contains
  the vast majority of fish, and is extremely diverse and abundant, being the largest class of
  extant vertebrates.
