level: phylum
common: Waterbears
info: >-
  Tardigrades are water-dwelling segmented microorganisms with eight legs.  They are considered to
  be extremophiles, as they can withstand temperatures from just above absolute zero to well above
  the boiling point of water, pressures about six times greater than those in the deepest ocean
  trenches, ionizing radiation hundreds of times stronger than the lethal dose for humans, as well
  as the vacuum of outer space.
