level: kingdom
info: >-
  Excavates are unicellular eukaryotes.  Most of them lack classical mitochondria, although most of
  them (perhaps all) retain a greatly modified form.  Most excavates also have flagella and a
  conspicuous ventral feeding groove.
