level: phylum
info: >-
  Arthropods form the biggest phylum of animals, with over one million described spceies, about 80%
  of all living animal species.  Arthropods are recognizable by their exoskeletons, segmented bodies
  and jointed appendages.  Among the arthropods are found insects, arachnids and crustaceans.
