level: life
info: >-
  Life has existed on Earth for at least 3.5 billion years. It is the only known place in the
  universe where this phenomenon exists.

  There is no absolute definition of life.  It is considered a characteristic of something that
  exhibits a 'sufficient' number of the following traits:

  - Homeostasis: Regulation of internal environment.

  - Organization: Composed of one or more cells.

  - Metabolism: Transformation of energy (anabolism and catabolism).

  - Growth: A higher rate of anabolism than catabolism.

  - Adaption: The ability to change in response to the environment.

  - Response to stimuli.

  - Reproduction.
