level: class
common: Lancelets
info: >-
  Lancelets are fish-like marine chordates, usually found half-buried in sand.  They are among the
  closest living non-vertebrate relatives of the vertebrates.
