level: phylum
common: Horseshoe worms
info: >-
  Phoronids are marine animals that filter-feed with a lophophore (a "crown" of tentacles), and
  which build tubes of chitin to support and protect their bodies.
