level: kingdom
info: >-
  Fungi, a large kingdom containing yeasts, molds and mushrooms, have cell walls containing chitin,
  unlike those of plants, which contain cellulose.  This separates them from slime molds and water
  molds, which are structurally similar.
