level: subkingdom
info: >-
  Eumetazoa contains all major animal groups except parazoans (sponges and placozoa), as well as
  many other obscure or exctinct life forms.  Eumetazoans have true tissues, neuroms and an embryo
  that goes through the gastrula stage.
