level: phylum
common: Moss animals
info: >-
  Moss animals are aquatic invertebrates usually about 0.5mm long.  They filter feed using a
  retractable lophophore.  Generally they are found in tropical waters, but some are found in
  oceanic trenches and some in polar waters.  Mostly (with one exception) they form colonies.
