level: superphylum
info: >-
  The deuterostomes form one of the two major lineages of bilateral animals (the other being the
  protostomes).  In deutorostomes, the first opening of the embryo becomes the anus, while in
  protostomes it becomes the mouth.
