level: kingdom
common: Animals
info: >-
  Animals are eukaryotic and multicellular organisms whose cells have membranes, and not walls.
  Animals are motile, if only at certain stages of life.  Animals are also heterotrophic, meaning
  that they feed directly on other organisms.
