level: phylum
common: Ringed worms
info: >-
  The annelids form a large phylum of segmented worms, including ragworms, earthworms and leeches.
  Annelids are bilaterally symmetric, and have parapodia for movement.
