level: class
common: Ray-finned fish
info: >-
  Ray-finned fishes have lepidotrichia or "fin rays", their fins being webs of skin supported by
  bony or horny spines ("rays"), as opposed to the fleshy fins of Sarcopterygii.
