level: kingdom
common: Plants
info: >-
  This kingdom is made up mostly of plants (Plantae), but also contains red and green algae, as well
  as the glaucophytes.  They share the common feature that chloroplasts are surrounded by two
  membranes, unlike three or four as in other groups.  Plant cells have cell walls containing
  cellulose.
