level: phylum
info: >-
  Brachiopods are marine animals with valves on the upper and lower surfaces, unlike left and right
  such as in bivalve molluscs.  They are hinged in the back, while the front can be opened for
  feeding.
