level: superphylum
info: >-
  Ecdysozoans form one of the three clades of protostomes.  Ecdysozoans have a three-layered (or
  four-layered) cuticle, which is periodically shed as the animal grows.  This group includes, among
  other things, arthropods and nematodes.
