level: phylum
common: Velvet worms
info: >-
  Velvet worms form a phylum of segmented organisms with tiny eyes, antennae and multiple pairs of
  legs and slime glands.  They have been compared to worms with legs, caterpillars and slugs.  They
  are most common in the tropical regions in the Southern Hemisphere.
