level: phylum
common: Molluscs
info: >-
  The molluscs form the largest marine phylum, with about 23% of all named marine organisms.
  Molluscs have a mantle with a significant cavity for breathing and excretio, as well as a radula.
  They can also be recognized by the structure of their nervous system.  Apart from this, molluscs
  display much variety.
