level: domain
info: >-
  Eukaryotic cells contain membrane-bound organelles, notably a cell nucleus (which gives them their
  name), but often also mitochondria and Golgi apparatuses.  Plants and algae also contain
  chloroplasts.

  All multicellular life is eukaryotic, but some eukaryotes are still unicellular.
