level: class
common: Lampreys
info: >-
  Hyperoartia is a disputed group of vertebrates that includes the lampreys and their extinct
  relatives, and together with the hagfish represent one of the oldest divergences among the
  vertebrates.
