level: phylum
common: Penis worms
info: >-
  Penis worms feed of mud, and live in it or in comparatively shallow waters up to 90m.  Some
  species are remarkably tolerant to hydrogen sulfide and anoxia.
