level: phylum
common: Jaw worms
info: >-
  Jaw worms are nearly microscopic marine animals inhabiting the sand and mud beneath shallow
  coastal waters.  They can survive in quite anoxic environments.
