level: domain
info: >-
  Archaea are prokaryotic organisms and very similar to bacteria.  However, they share some traits
  with eukaryotic organisms.  In particular, archaea possess genes and certain enzymes involved in
  transcription.  Archaea can also make use of more energy sources than eukaryotes.

  Archaea were initially considered to be extremophiles, but have since been found in many more
  regular habitats, mostly in the ocean.
