level: phylum
common: Flatworms
info: >-
  Flatworms are bilateral, unsegmented and soft-bodies invertebrates without a body cavity.  They
  have no specialized circulatory or respitarory organs, which restricts their body shape.  Oxygen
  and nutrients pass through their bodies by diffusion.
