level: subkingdom
info: >-
  Parazoans are nonmicroscopic animals that, like other animals, have differentiated cells, but lack
  tissues and organs.  The only surviving parazoans are the sponges and the Trichoplax.
