level: phylum
common: Ribbon worms
info: >-
  Nemerteans are generally less than 20cm long (although one specimen has been estimated at 54m).
  Most are very slim, usually only a few millimetres wide.  They move slowly, using external cilia
  to glide on a trail of slime.  Most of them are carnivores, feeding on annelids, clams and
  crustaceans.
