level: phylum
common: Sponges
info: >-
  Sponges form the vast majority of the parazoans, and are multicellular organisms with bodies full
  of pores and channels, allowing water to circulate through.  They do not have nervous, digestive
  or circulatory systems, and rely instead on maintaining a constant water flow to obtain food and
  remove waste.
