level: class
common: Cartilaginous fish
info: >-
  Cartilaginous fishes (sharks, rays, skates and chimaeras) are jawed fish with paired fins and
  nares, scales, a chambered heart and skeletons made of cartilage rather than bone.
