level: phylum
common: Hairybacks
info: >-
  Hairybacks are microscopic worm-like animals widely distributed in freshwater and marine
  environments.  They live within the layer of tiny organisms found on the seabed.
