level: phylum
info: >-
  Chordates are animals with, at some point in their life:

  - A notochord, which develops into the spine of vertebrates.

  - A dorsal neural tube, which develops into the spinal cord.

  - Pharyngeal slits (i.e. gills, among fish).

  - A post-anal tail.

  - An endostyle.
