level: phylum
common: Thorny-headed worms
info: >-
  These parasitic worms are characterized by the presence of a proboscis, armed with spines, which
  it uses to pierce and hold the gut of its host.
