level: phylum
common: Comb jellies
info: >-
  Comb jellies are the largest animals swimming by means of cilia.  Almost all ctenophores are
  predators, feeding on larvae and rotifers to small crustaceans.
