level: phylum
info: >-
  Hemichordates have a tripartite body organization, and are the closest relatives of the chordates
  among invertebrates.  This phylum contains the acorn worms (Enteropneusta).
