level: kingdom
info: >-
  Chromaelveolates form a disputed and very diverse kingdom of plant-like multicellular organisms.
  The only common features are that all chromalveolates use chlorophylls a and c, and have cellulose
  in most cell walls.
