level: class
info: >-
  Reptiles comprise today's turtles, crocodilians, snakes and lizards.  A monophyletic clade would
  have to include birds, but birds are commonly not considered reptiles, although like reptiles they
  have scales and lay eggs.

  Commonly, a reptile is any tetrapod whose eggs have additional membranes, originally allowing them
  to lay eggs on land, that is neither a mammal nor a bird.
