level: phylum
info: >-
  Entoprocta are mostly sessile aquatic animals from 0.1 to 7mm long.  They are goblet-shaped, on
  relatively long stalks, with tentacles whose cilia generate currents that draw food towards the
  mouth.  Both the mouth and the anus lie inside the crown, hence their name, which means "anus
  inside".
