level: class
common: Larvaceans
info: >-
  Larvaceans are solitary free-swimming tunicates, which, unlike most other tunicates, live in the
  pelagic zone.  They are transparent planktonic animals, generally less than 1cm long, excluding
  the tail.
