level: phylum
info: >-
  Cnidarians are radially symmetric organisms similar to comb jellies.  Unlike comb jellies,
  cnidarians feature cnidocytes: specialized cells used for capturing prey.  The phylum contains
  mostly jellyfish and corals.
