level: class
info: >-
  Mammals are endothermic amniotes (capable of giving birth away from water, unlike amphibians)
  distinguished from reptiles and birds by hair, three middle ear bones, mammary glands as well as a
  neocortex.
