level: domain
common: Bacteria
info: >-
  Bacteria form a large and varied domain of prokaryotes (single-celled organisms without a
  membrane-bound cell nucleus).  They were one of the first forms of life to appear and exist today
  in most of the habitats on Earth.  They often form symbiotic or parasitic relationships with
  plants and animals.

  There are an estimated 5×10³⁰ bacteria, yielding a biomass exceeding that of all plants and
  animals combined.
