level: superphylum
info: >-
  Lophotrochozoans form one of the major groups of protostome animals.  It was discovered based on
  molecular data.  They contain molluscs, brachiopods, moss animals and ringed worms, among others.
